### ISSUE TITLE
Assertion "head != NULL" failed in esp-idf/components/heap/multi_heap_poisoning.c

### ISSUE THREAD

**Issue by Bascy** [esp32m/logging#1]
Trying to incoorporate logging to Serial and UDP into my existing ESP32 arduino project but getting and assertion failure on the first use of log_i.

```c++
  WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.println("Connecting to WiFi..");
  }
 
  Serial.println("Connected to the WiFi network");

  // send log messages to standard output (Serial)
  // esp32m::Logging::addAppender(&esp32m::ETSAppender::instance());
  
  // send log messages to 192.168.1.1:1234 in the form of UDP packets
  esp32m::Logging::addAppender(new esp32m::UDPAppender("192.168.2.19", 1234));
   // redirect standard output to appenders
  esp32m::Logging::hookUartLogger();

  log_i("-------------------------------------------------"); // <== assertion failure!
```

*Full Error:*
> assertion "head != NULL" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_poisoning.c", line 214, function: multi_heap_free
> 
> Backtrace: 0x4008d3a0:0x3ffb1cb0 0x4008d5d1:0x3ffb1cd0 0x4011a0f3:0x3ffb1cf0 0x4008d015:0x3ffb1d20 0x40084fc2:0x3ffb1d40 0x400853c9:0x3ffb1d60 0x4000bec7:0x3ffb1d80 0x400e538b:0x3ffb1da0 0x400e501e:0x3ffb1e20 0x400e5159:0x3ffb1e40 0x40007c69:0x3ffb1e70 0x40008106:0x3ffb1e90 0x400e7026:0x3ffb1f20 0x400db40a:0x3ffb1f80 0x400e71b7:0x3ffb1fb0 0x40089819:0x3ffb1fd0
>   #0  0x4008d3a0:0x3ffb1cb0 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
>   #1  0x4008d5d1:0x3ffb1cd0 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
>   #2  0x4011a0f3:0x3ffb1cf0 in __assert_func at /Users/ivan/e/newlib_xtensa-2.2.0-bin/newlib_xtensa-2.2.0/xtensa-esp32-elf/newlib/libc/stdlib/../../../.././newlib/libc/stdlib/assert.c:63 (discriminator 8)
>   #3  0x4008d015:0x3ffb1d20 in multi_heap_free at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_poisoning.c:315      
>   #4  0x40084fc2:0x3ffb1d40 in heap_caps_free at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps.c:131
>   #5  0x400853c9:0x3ffb1d60 in _free_r at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/syscalls.c:42
>   #6  0x4000bec7:0x3ffb1d80 in ?? ??:0
>   #7  0x400e538b:0x3ffb1da0 in esp32m::UDPAppender::append(esp32m::LogMessage const*) at .pio\libdeps\debug\ESP32 logger\src/udp-appender.cpp:39
>   #8  0x400e501e:0x3ffb1e20 in esp32m::Logger::log(esp32m::LogLevelo\libdeps\debug\ESP32 logger\src/logging.cpp:464
>   #9  0x400e5159:0x3ffb1e40 in esp32m::SerialHook::hookImpl(char) aESP32 logger\src/logging.cpp:464
>       (inlined by) esp32m::SerialHook::hook(char) at .pio\libdeps\d/logging.cpp:505
>   #10 0x40007c69:0x3ffb1e70 in ?? ??:0
>   #11 0x40008106:0x3ffb1e90 in ?? ??:0
>   #12 0x400e7026:0x3ffb1f20 in log_printf at C:\users\bas\.platform-arduinoespressif32\cores\esp32/esp32-hal-uart.c:492
>   #13 0x400db40a:0x3ffb1f80 in setup() at src/main.cpp:32 (discrimi
>   #14 0x400e71b7:0x3ffb1fb0 in loopTask(void*) at C:\users\bas\.plaework-arduinoespressif32\cores\esp32/main.cpp:14
>   #15 0x40089819:0x3ffb1fd0 in vPortTaskWrapper at /home/runner/woruilder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.

**Comment by dyarkovoy** [comment]
Hi, I made some changes, please try version 1.0.2.

**Comment by Bascy** [comment]
Solved
