### ISSUE TITLE
File on SD Card is created but no logging lines are written to the file

### ISSUE THREAD

**Issue by wernerschmitz** [esp32m/logging#10]
Hi,
I was trying to use your Library since it looked a very nice and complete logging tool.
When I setup a test project in pio, added SD card handling, it instantly worked.
Then after a few rebuilds it is only creating the file (Or more files if maxFiles is used),
but without any content. The serial logging works.
I hope you can help.

**Code**:
_

```
#define SD_MISO 2
#define SD_MOSI 15
#define SD_SCLK 14
#define SD_CS 13
#include "SD.h"
#include "SPI.h"

using namespace esp32m;

void setup()
{
  SPI.begin(SD_SCLK, SD_MISO, SD_MOSI, SD_CS);
      delay(50);
        if (!SD.begin(SD_CS)) {
            Serial.println("SDCard MOUNT FAIL");
        } else {
            //isSdMounted       = true;
            uint32_t cardSize = SD.cardSize() / (1024 * 1024);
            String str        = "SDCard Size: " + String(cardSize) + "MB";
            Serial.println(str);
        }
  SPIFFS.begin(true);
  // send log messages to file "mylog" on the SPIFFS
  Logging::addAppender(new FSAppender(SD, "/mylog",3));
  // send log messages to standard output (Serial)
  Logging::addAppender(&ETSAppender::instance());
  // send log messages to 192.168.1.1:1234 in the form of UDP packets
 // Logging::addAppender(new UDPAppender("192.168.1.1", 1234));
  // redirect standard output to appenders
  Logging::hookUartLogger();
  // now use log_X macros to forward log messages to the registered appenders
  log_i("hello world!");
}

void loop()
{
  delay(1000);
  log_i("called from loop");
}
```

_

**Platformio.ini**:

_[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = esp32m/ESP32 logger@^1.0.3
            WiFi
build_flags = -D CORE_DEBUG_LEVEL=5
            ;-DLOGGING_REDEFINE_LOG_X_

**Comment by dyarkovoy** [comment]
Hi, try using the library from github directly in lib_deps. I remember fixing this glitch a while ago, but I'm not sure if the lib in platformio repository got updated

**Comment by wernerschmitz** [comment]
Yep, that fixed it.
Tnx for the (very) quick response!
