### ISSUE TITLE
Adding FunctionAppender

### ISSUE THREAD

**Issue by jordyneefs** [esp32m/logging#11]
Hi, 

I want to make a FunctionAppender so I can call a custom function when a log is called.

function-appender.hpp:
```cpp
#pragma once

#include "logging.hpp"
#include <functional>

namespace esp32m {

class FunctionAppender : public LogAppender {
public:
    FunctionAppender(const FunctionAppender&) = delete;
    static FunctionAppender& instance(std::function<void()> func);

private:
    FunctionAppender(std::function<void()> func)
    : appendFunction(func) {
    }
    std::function<void()> appendFunction;

protected:
    virtual bool append(const LogMessage* message);
};

} // namespace esp32m
```

function-appender.cpp:
```cpp
#include "function-appender.hpp"
#include <iostream>
#include <string.h>

namespace esp32m {
FunctionAppender& FunctionAppender::instance(std::function<void()> func) {
    static FunctionAppender i(func);
    return i;
}

bool FunctionAppender::append(const LogMessage* message) {
    if (message && appendFunction) {
        std::string messageToFormat = message->message();
        size_t positionToCut        = messageToFormat.find(": ");

        const char* messageToLog = messageToFormat.substr(positionToCut + 2).c_str();

        auto l = strlen(messageToLog);
        for (auto i = 0; i < l; i++)
            ets_write_char_uart(messageToLog[i]);
        ets_write_char_uart('\n');

        appendFunction();
    }
    return true;
}
} // namespace esp32m
```

main.cpp:
```cpp
#include <ets-appender.hpp>
#include <fs-appender.hpp>
#include <function-appender.hpp>
#include <logging.hpp>
#include <udp-appender.hpp>

using namespace esp32m;

void handleLog() {
    Serial.print("Handle Log: ");
}

void setup() {
    Serial.begin(SERIAL_BAUDRATE);
    Logging::addAppender(&ETSAppender::instance());
    Logging::hookUartLogger();
    Logging::addAppender(&FunctionAppender::instance(handleLog));
    log_i("hello world!");
}
```

For testing purposes I also do the ets_write_char_uart so i know that my appender is executed.
When I comment out the call of appendFunction() in my function-appender.cpp, everything works. When I uncomment the call my ESP stops at this line, no crash but just stops.

**Comment by dyarkovoy** [comment]
Hi, try replacing `Serial.print("Handle Log: ");` in `handleLog()` by `ets_write_char_uart()`, will it work?

**Comment by jordyneefs** [comment]
This works but my goal is to send my log messages to bluetooth, I have a class with a function sendBluetoothMessage, the goal is to call this function with some parameters. So I thought if I can call a simple function I can build on that to implement my goal.

my goal is something like this:
function-appender.cpp:
```cpp
appendFunction(messageToLog);
```

main.cpp:
```cpp
void handleLog(const char* messageToLog) {
    BluetoothMessage logMessage;
    logMessage.type    = "LOG";
    logMessage.command = "INFO";
    logMessage.value = messageToLog;

    InterCommunicationManager::getInstance().sendBluetoothMessage(logMessage);
}
```

something like this

**Comment by dyarkovoy** [comment]
It may work with bluetooth. I think the problem is related specifically to `Serial.print()` that you are calling in `handleLog()`. You hook UART logger, which means everything you send to UART via `Serial.print()` goes through the logger and ultimately ends up in your `handleLog` where you call `Serial.print()` again. There you have either a deadlock or an endless loop

**Comment by jordyneefs** [comment]
Okay, so if I just use the sendBluetoothMessage function it kinda works. The data is send but I get one problem that I dont have when I use the function somewhere else. But I will look into that. But if I understand, ther cannot be any Serial.print() in everything the handleLog calls, also not in any nested code?

**Comment by dyarkovoy** [comment]
not only `Serial.print()`, but any other fn that writes to UART

**Comment by jordyneefs** [comment]
Okay, does that mean also a ESP_LOGI? Does this cause a loop? I think it does

**Comment by dyarkovoy** [comment]
Yes, it should. 
Ideally, you should set up a separate task, notify it from handleLog() and call your functions in that task.

**Comment by jordyneefs** [comment]
yeah i could do that, one task shouln't be any problem, I tried to split up my whole project with freertos but my knowledge is not good enough to do it

**Comment by jordyneefs** [comment]
If I want to create a task for this, should I use a Queue than because i have to pass data? So the handleLog sends data do the queue, a task listens to this queue and if it see something it wil call the sendBluetoothMessage function?

**Comment by dyarkovoy** [comment]
Yes, you can do that with the queue

**Comment by jordyneefs** [comment]
Okay thank you for your help
