### ISSUE TITLE
Problem debug level

### ISSUE THREAD

**Issue by jordyneefs** [esp32m/logging#12]
I have a problem with setting my debug level.

in my setup i do this:
```cpp
Logging::addAppender(&ETSAppender::instance());
Logging::hookUartLogger();
Logging::addAppender(&FunctionAppender::instance(handleLog));

log_e("hello world!");
log_w("hello world!");
log_i("hello world!");
log_d("hello world!");
log_v("hello world!");
```

My build flags in platformio.ini:
```bash
build_flags =
    -D CORE_DEBUG_LEVEL=2
    -D LOGGING_REDEFINE_LOG_X
```

Output:
```bash
0:00:00:00.0396 E system  hello world!
0:00:00:00.0398 W system  hello world!
0:00:00:00.0401 I system  hello world!
0:00:00:00.0405 D system  hello world!
```

When I remove the LOGGING_REDEFINE_LOG_X the loglevel works but the format is different and i prefer the first format.

```bash
0:00:00:00.0396 D system  [   396][E][main.cpp:323] setup(): hello world!
0:00:00:00.0401 D system  [   401][W][main.cpp:324] setup(): hello world!
```

So is it possible to set the log level when using LOGGING_REDEFINE_LOG_X? 

Also strange, when I set LOGGING_REDEFINE_LOG_X, the verbose logs are not shown.

**Comment by dyarkovoy** [comment]
Please use `Logging::setLevel()` in your app to set logging level: https://github.com/esp32m/logging/blob/9856aa10f5c0e75a4e380d7be342291c50e78ed1/include/logging.hpp#L286

**Comment by jordyneefs** [comment]
Okay thank you, I overlooked that function, now it works.

**Comment by jordyneefs** [comment]
When I do Logging::setLevel(LogLevel::Verbose); it does weird things, this is my output:

```bash
0:00:000:00:00:00.0395 E system  hello world!
0:00:00:00.0396 W system  hello world!
0:00:00:00.0396 I system  hello world!
0:00:00:00.0396 D system  hello world!
0:00:00:00.0398 ? system  hello world!
```

The other levels works as expected

**Comment by dyarkovoy** [comment]
Try using the library from github directly in lib_deps. I remember fixing this glitch a while ago, but I'm not sure if the lib in platformio repository got updated

**Comment by jordyneefs** [comment]
I've always used the lib from github directly, a few day ago I dowloaded the repo as zip and included it in the lib folder in platformIO because i've added my own appender. So I think this is the latest version

**Comment by dyarkovoy** [comment]
Ok I made some changes, please try now

**Comment by jordyneefs** [comment]
The loglevel seems to work now. One bug i think, when I set the loglevel to Debug my output is:
```bash
0:00:00:00.0393 E system  hello world!
0:00:00:00.0394 W system  hello world!
0:00:00:00.0394 I system  hello world!
0:00:00:00.0394 D system  hello world!
``` 
When I set it to Verbose the output is
```bash
0:00:000:00:00:00.0394 E system  hello world!
0:00:00:00.0395 W system  hello world!
0:00:00:00.0395 I system  hello world!
0:00:00:00.0395 D system  hello world!
0:00:00:00.0397 V system  hello world!
``` 
So it seems something goes wrong with the time in the error log when loglevel is set to Verbose

**Comment by dyarkovoy** [comment]
This is not related to the time. This kind of output appears when different tasks try to write to UART at the same time. Maybe you are logging from the different threads while not using internal queue, see the description of the `Logger::useQueue()`: https://github.com/esp32m/logging/blob/ddeb4fe41ed5004b311bb7eeec3e7c2335316713/include/logging.hpp#L301
or some other function tries to write to UART at the same time when the logger does.

**Comment by jordyneefs** [comment]
Found the problem, i had a log before setting the logger etc, now everything works as it should, ty very much
