### ISSUE TITLE
loggin to multiple appenders  at the same time

### ISSUE THREAD

**Issue by emonget** [esp32m/logging#3]
Hi,

Is it possible to use a single log command to send to multiple appenders at the same time?

From the docs, I'm not sure if we need one line `log_i("hello world!");` per appenders (with 'i' targeting the appender)

**Comment by dyarkovoy** [comment]
Hi, yes, a single command sends to multiple appenders at the same time, that's the idea behind the logger - output to multiple appenders. You can use one of the` log_x` commands to do that (where `x` denotes log level - error, warning, info, debug, verbose). For example, `log_i("hello world!");` will send info-level message "hello world" to all appenders. Different log levels allow to conveniently classify log messages by their importance. The output can be limited based on the level of the message (for example, output only error and warning messages and discard the rest). This is done by setting effective log level in the `Logger` instance (see `Logger::setLevel`)

**Comment by emonget** [comment]
Thanks for the clear explanation
I misunderstood what the `x` was meaning.. from what you just explained, it is for targeting log level 
Will give a try and mark as solved.
