### ISSUE TITLE
Logging to SD via SD_MMC

### ISSUE THREAD

**Issue by PureTek-Innovations** [esp32m/logging#6]
Hi
I'm trying to log to an SD card using the SD_MMC library.
I can successfully mount the SD card in setup like this

`void setupSD(){
  Serial.begin(115200);
    pinMode(SDCARD_MISO, INPUT_PULLUP);
    if(!SD_MMC.begin()){
        Serial.println("Failed to mount card");
        return;
    }
    uint8_t cardType = SD_MMC.cardType();
 
    Serial.print("\nCard Type: ");
     
    if(cardType == CARD_NONE){
        Serial.println("No card attached");
        return;
    }
    if(cardType == CARD_MMC){
        Serial.println("MMC");
    } else if(cardType == CARD_SD){
        Serial.println("SDSC");
    } else if(cardType == CARD_SDHC){
        Serial.println("SDHC");
    } else {
        Serial.println("UNKNOWN");
    }
 
    uint64_t cardSize = SD_MMC.cardSize();
    int cardSizeInMB = cardSize/(1024 * 1024);
     
    Serial.print("Card size: ");
    Serial.println(cardSizeInMB);
 
 
    uint64_t bytesAvailable = SD_MMC.totalBytes(); 
    int bytesAvailableInMB = bytesAvailable/(1024 * 1024);
 
    Serial.print("MB available: ");
    Serial.println(bytesAvailableInMB);
 
 
    uint64_t bytesUsed = SD_MMC.usedBytes();
    int bytesUsedInMB = bytesUsed/(1024 * 1024);
 
    Serial.print("MB used: ");
    Serial.println(bytesUsedInMB);
}`

Then I am adding the appender like this:
`Logging::addAppender(new FSAppender(SD_MMC,"/newlog.txt"));`

The library creates the log file if it doesn't exist, but doesn't seem to write any data to it.

Am I doing something wrong?
Thanks

**Comment by dyarkovoy** [comment]
Hi, I added flush() after file write, please see if it makes any difference in your case

**Comment by PureTek-Innovations** [comment]
That got it working.
Thank you very very much
