### ISSUE TITLE
[Question] Use Logging library for other purpose...

### ISSUE THREAD

**Issue by GregAscolab** [esp32m/logging#8]
Hi,

I use logging library for "debug/log" purpose as it has been design for.  
I create my own appender to send log data to my MQTT server (Thingsboard.io) in its own JSON format.  
As I'm using battery powered board and 4G/LTE modem for connection, I like the useQueue and BufferedAppender to manage lost of connection and modem setup time.  
It works well for the log messages.  

So my idea is to use exactly same principle for "telemetry" data : sensor, IO, etc...  

Is it possible to create multiple "Logging / Logger" with their own Queue size, appenders (mqtt, filesystem...) ... ?  
If yes, how to do it and "send" data to logger ?  

I try to create multiple instance of "Logging" class, but I think it's not the right way, isn't it ? It seems to me that "Logging" class is kind of singleton class and every instance are linked together.  

Thanks for your feedback, and example to follow.

**Comment by dyarkovoy** [comment]
Hi, you're right, Logging class is a singleton, and it is not possible to
create multiple instances of Logging with their own appenders/queue sizes.
I never thought that one application might need a different set of
appenders for different logging tasks. And if I understand your
explanations correctly, it may not be a good idea to use logger for
telemetry, it's a different task IMO.
You can check how I do it in esp32 manager (https://esp32m.com), there is a
set of tools to set up sensors and send out telemetry data via MQTT, and
there's integration example for Home Assistant.

ср, 7 лют. 2024 р. о 17:03 GregAscolab ***@***.***> пише:

**Comment by GregAscolab** [comment]
Hi,
I understand that debug/log is not the same task as collecting and sending telemetry/sensor values.
But... the principle is quite the same not ?
1. Collect something : log message/sensor value
2. Push it to "appenders" : to file system, mqtt, udp, change output format, etc...

And in the middle, you need to manage readiness of appenders, else store to queue/buffer : No network (poor wifi, no ethernet cable, no 4G/LTE network, etc...), hardware not ready...
And this is managed by Queue/BufferedAppender.

So that's why I wanted to reuse same code... because everything is already done ;-)

In your eps32m, I can see some "Sensor" object (I can't find definition yet...), and I can see how you send data to ha, or other mqtt broker. This is the same way I do it right now : just prepare your payload, then "publish"... ok but what happen if you have no internet connection ? I loose my data ! And as I want to send my data on changed state only, I can loose important information.

Think about a simple light ON/OFF switch state I want to sent to server to compute time the ligth is ON or OFF : If I loose one of the state, the time computation is totally false. Especially if the state doesn't change quite often (2x times per day !).
That's why I need to buffer with a timestamp until the connection is back, and then send every record event to the server.

So do you think it's possible to update a little the "logging" library to keep the same principle as today, but could create multiple instance of "Logging" object ? Create a derivative class ?
At least one "Logging" will stay the logger of debug/log : managing Serial hook,... like now, and it can stay as a singleton instance.
And other derivative instances will be simplest logging class, without Serial hook, and with a simple "log()" method to log something to appenders...
```
SimpleLogging myLogger;
myLogger.useQueue(1024);
myLogger.addBufferredAppender(&myOwnMqttAppender, 1024, false);
myLogger.addBufferredAppender(&myOwnCSVFileAppender, 1024, true);

myLogger.log("{\"key\":%i}", myValue);
```
Then the magical stuff do the job :
* Enqueue
* Auto dequeue in its own task, periodically...
* Check if appender is ready, else keep it buffered

Done !

**Comment by dyarkovoy** [comment]
Ok, I see. You have some logic implemented on the device, some logic on a server, and you're trying to sync it. I usually try to avoid that and have all logic either on the device, or elsewhere, but on a single computation unit, not scattered.
You are welcome to make Logging class support multiple instances (by moving globals inside the class and by referencing specific Logging instance from the Logger's and maybe Appender's). If you can keep it backward compatible - feel free to submit PR.  I don't use this lib, as I have a different logger implementation in esp32m, but someone else may be using it. If your changes break compatibility, then just use your own fork
